### PR TITLE
fix(login): fixed undefined error. fixed login logic

### LINKED ISSUE #14: [bug `/login`]  Cannot read properties of undefined (reading `id`)
### Steps to produce

1. Make a request to `POST /login` and you see the error.

### Screenshots

image

### PR DESCRIPTION
**Pull request by TotalElderBerry**
closes #14

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -13,6 +13,7 @@ const app = express();
 // Set the port
 const port = process.env.PORT || 4000;
 
+app.use(express.json())
```
Comment (mavyfaby) [inline src/index.ts]: Use `express.urlencoded()` instead of `express.json()` to avoid CORS preflight request.

**Review by mavyfaby — CHANGES_REQUESTED** [review]

**Review by mavyfaby — APPROVED** [review]
LGTM
